truncate table user;
insert into user (user_id, user_name, password, expiration_date, first_name, last_name, mail_address, update_date_time) values (1, 'admin', 'admin', null, '管理者', 'システム', 'admin@test.co.jp', current_timestamp);
insert into user (user_id, user_name, password, expiration_date, first_name, last_name, mail_address, update_date_time) values (2, 'masudken', '1234', null, '賢一', '増田', 'masuda@gfam.co.jp', current_timestamp);
insert into user (user_id, user_name, password, expiration_date, first_name, last_name, mail_address, update_date_time) values (3, 'kanako', '1234', null, '夏菜子', '百田', 'kanako@test.co.jp', current_timestamp);
insert into user (user_id, user_name, password, expiration_date, first_name, last_name, mail_address, update_date_time) values (4, 'shiori', '1234', null, '詩織', '玉井', 'shiori@test.co.jp', current_timestamp);
insert into user (user_id, user_name, password, expiration_date, first_name, last_name, mail_address, update_date_time) values (5, 'ayaka', '1234', null, '彩夏', '佐々木', 'ayaka@test.co.jp', current_timestamp);
insert into user (user_id, user_name, password, expiration_date, first_name, last_name, mail_address, update_date_time) values (6, 'anka', '1234', null, '杏果', '有安', 'anka@test.co.jp', current_timestamp);
insert into user (user_id, user_name, password, expiration_date, first_name, last_name, mail_address, update_date_time) values (7, 'reni', '1234', null, 'れに', '高城', 'reni@test.co.jp', current_timestamp);
insert into user (user_id, user_name, password, expiration_date, first_name, last_name, mail_address, update_date_time) values (8, 'akari', '1234', null, 'あかり', '早見', 'akari@test.co.jp', current_timestamp);
insert into user (user_id, user_name, password, expiration_date, first_name, last_name, mail_address, update_date_time) values (9, 'atsuko', '1234', null, '敦子', '前田', 'atsuko@test.co.jp', current_timestamp);
insert into user (user_id, user_name, password, expiration_date, first_name, last_name, mail_address, update_date_time) values (10, 'yuko', '1234', null, '優子', '大島', 'yuko@test.co.jp', current_timestamp);
insert into user (user_id, user_name, password, expiration_date, first_name, last_name, mail_address, update_date_time) values (11, 'mayu', '1234', null, '麻友', '渡辺', 'mayu@test.co.jp', current_timestamp);
insert into user (user_id, user_name, password, expiration_date, first_name, last_name, mail_address, update_date_time) values (12, 'yuki', '1234', null, '由紀', '柏木', 'yuki@test.co.jp', current_timestamp);
insert into user (user_id, user_name, password, expiration_date, first_name, last_name, mail_address, update_date_time) values (13, 'haruna', '1234', null, '陽菜', '小嶋', 'haruna@test.co.jp', current_timestamp);
insert into user (user_id, user_name, password, expiration_date, first_name, last_name, mail_address, update_date_time) values (14, 'minami', '1234', null, 'みなみ', '高橋', 'minami@test.co.jp', current_timestamp);
insert into user (user_id, user_name, password, expiration_date, first_name, last_name, mail_address, update_date_time) values (15, 'tomomi', '1234', null, '友美', '板野', 'tomomi@test.co.jp', current_timestamp);
insert into user (user_id, user_name, password, expiration_date, first_name, last_name, mail_address, update_date_time) values (16, 'rino', '1234', null, '莉乃', '指原', 'rino@test.co.jp', current_timestamp);
insert into user (user_id, user_name, password, expiration_date, first_name, last_name, mail_address, update_date_time) values (17, 'mariko', '1234', null, '麻里子', '篠田', 'mariko@test.co.jp', current_timestamp);
insert into user (user_id, user_name, password, expiration_date, first_name, last_name, mail_address, update_date_time) values (18, 'haruka', '1234', null, '遥香', '島崎', 'haruka@test.co.jp', current_timestamp);
commit;
